include_guard(GLOBAL)

set(MD3_QT_VERSION "AUTO" CACHE STRING "Qt major version: AUTO, 5, or 6")
set_property(CACHE MD3_QT_VERSION PROPERTY STRINGS AUTO 5 6)

set(_md3_qt_pick "${MD3_QT_VERSION}")
string(TOUPPER "${_md3_qt_pick}" _md3_qt_pick)

if (_md3_qt_pick STREQUAL "AUTO")
    find_package(Qt6 QUIET COMPONENTS Core)
    if (Qt6_FOUND)
        set(MD3_QT_MAJOR 6)
    else()
        find_package(Qt5 REQUIRED COMPONENTS Core)
        set(MD3_QT_MAJOR 5)
    endif()
elseif (_md3_qt_pick STREQUAL "6")
    find_package(Qt6 REQUIRED COMPONENTS Core)
    set(MD3_QT_MAJOR 6)
elseif (_md3_qt_pick STREQUAL "5")
    find_package(Qt5 REQUIRED COMPONENTS Core)
    set(MD3_QT_MAJOR 5)
else()
    message(FATAL_ERROR "MD3_QT_VERSION must be AUTO, 5, or 6 (got: ${MD3_QT_VERSION})")
endif()

set(MD3_QT_MAJOR "${MD3_QT_MAJOR}" CACHE INTERNAL "Resolved Qt major version")
set(MD3_QT_PACKAGE "Qt${MD3_QT_MAJOR}" CACHE INTERNAL "Resolved Qt package prefix")

function(md3_find_qt)
    set(_components ${ARGV})
    if (NOT _components)
        message(FATAL_ERROR "md3_find_qt requires at least one Qt component")
    endif()
    find_package(${MD3_QT_PACKAGE} REQUIRED COMPONENTS ${_components})
endfunction()

function(md3_qt_target out_var module_name)
    set(${out_var} "${MD3_QT_PACKAGE}::${module_name}" PARENT_SCOPE)
endfunction()
